apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-monkey
  labels:
    app: book-monkey
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-monkey
  template:
    metadata:
      labels:
        app: book-monkey
    spec:
      containers:
        - name: book-monkey
          image: registry.akogare.de/book-monkey:1.0.0
          imagePullPolicy: Always

          ports:
            - containerPort: 80
              protocol: TCP
              name: tryhard
              # ServiceType is NodePort listening on port 30080 and name is 'tryhard'

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: akogare-registry
